// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD4ddLbVWWRmJvlm05981IF3ft0teVpEc',
    appId: '1:438085580346:android:9206f7cb8f36a2295ca703',
    messagingSenderId: '438085580346',
    projectId: 'lyza-insta-clone',
    storageBucket: 'lyza-insta-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8NgZHumelgRwsmURzXYu1RshckuO0llc',
    appId: '1:438085580346:ios:4108c78ca47ad5655ca703',
    messagingSenderId: '438085580346',
    projectId: 'lyza-insta-clone',
    storageBucket: 'lyza-insta-clone.appspot.com',
    iosClientId: '438085580346-ofki0d0s2i2cft9vtteulmipov0o7l0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.myUiDesignApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwbZHtGh01LCjNTXpR7xUmHthvDz49tMU',
    appId: '1:438085580346:web:95315f13e7927c7d5ca703',
    messagingSenderId: '438085580346',
    projectId: 'lyza-insta-clone',
    authDomain: 'lyza-insta-clone.firebaseapp.com',
    storageBucket: 'lyza-insta-clone.appspot.com',
    measurementId: 'G-9F64G549Y8',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwbZHtGh01LCjNTXpR7xUmHthvDz49tMU',
    appId: '1:438085580346:web:1d898ad6c3e2de8a5ca703',
    messagingSenderId: '438085580346',
    projectId: 'lyza-insta-clone',
    authDomain: 'lyza-insta-clone.firebaseapp.com',
    storageBucket: 'lyza-insta-clone.appspot.com',
    measurementId: 'G-4P03Z1BJ6C',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8NgZHumelgRwsmURzXYu1RshckuO0llc',
    appId: '1:438085580346:ios:4108c78ca47ad5655ca703',
    messagingSenderId: '438085580346',
    projectId: 'lyza-insta-clone',
    storageBucket: 'lyza-insta-clone.appspot.com',
    iosClientId: '438085580346-ofki0d0s2i2cft9vtteulmipov0o7l0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.myUiDesignApp',
  );

}